name: Test Environment Variables

on: [push]

jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Display environment variable
        run: echo "PORT is ${{ secrets.PORT }}"
